all : prob1 prob2 prob3 prob4

prob1: cscd340Lab8prob1.c
	gcc -o prob1 cscd340Lab8prob1.c -lpthread

prob2 : cscd340Lab8prob2.c
	gcc -o prob2 cscd340Lab8prob2.c -lpthread
     
prob3: cscd340Lab8prob3.c
	gcc -o prob3 cscd340Lab8prob3.c -lpthread

prob4: cscd340Lab8prob4.c
	gcc -o prob4 cscd340Lab8prob4.c -lpthread
     
clean:
	rm *.o
